//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerenciador.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_curso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_curso()
        {
            this.tb_detalhesResultado = new HashSet<tb_detalhesResultado>();
            this.tb_notaMec = new HashSet<tb_notaMec>();
        }
    
        public int cur_in_id { get; set; }
        public int areaCur_in_id { get; set; }
        public string cur_st_nome { get; set; }
        public string cur_st_desc { get; set; }
        public string cur_st_duracao { get; set; }
        public string cur_img_prof { get; set; }
        public string cur_st_tipo { get; set; }
        public byte cur_in_atribuidoNotaMec { get; set; }
        public int cur_in_valorMin { get; set; }
        public int cur_in_valorMax { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_detalhesResultado> tb_detalhesResultado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_notaMec> tb_notaMec { get; set; }
    }
}
