//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerenciador.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_notaMec
    {
        public int notaMecFacul_in_id { get; set; }
        public int notaMecCur_in_id { get; set; }
        public int notaMec_in_valor { get; set; }
    
        public virtual tb_curso tb_curso { get; set; }
        public virtual tb_faculdade tb_faculdade { get; set; }
    }
}
