//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerenciador.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_resposta
    {
        public int resp_in_id { get; set; }
        public int perg_in_id { get; set; }
        public string resp_st_desc { get; set; }
        public double resp_re_resExatas { get; set; }
        public double resp_re_resHumanas { get; set; }
        public double resp_re_resBiologicas { get; set; }
    
        public virtual tb_pergunta tb_pergunta { get; set; }
    }
}
