//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerenciador.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_teste
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_teste()
        {
            this.tb_detalhesResultado = new HashSet<tb_detalhesResultado>();
        }
    
        public int teste_in_id { get; set; }
        public int userTeste_in_id { get; set; }
        public System.DateTime teste_dt_inicio { get; set; }
        public Nullable<System.DateTime> teste_dt_final { get; set; }
        public byte teste_bool_novoTeste { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_detalhesResultado> tb_detalhesResultado { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
