//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerenciador.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_tipoContatoFaculdade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_tipoContatoFaculdade()
        {
            this.tb_contatoFaculdade = new HashSet<tb_contatoFaculdade>();
        }
    
        public int tipoContFac_in_id { get; set; }
        public string tipoContFac_st_nome { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_contatoFaculdade> tb_contatoFaculdade { get; set; }
    }
}
