//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerenciador.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_usuario()
        {
            this.tb_detalhesResultado = new HashSet<tb_detalhesResultado>();
            this.tb_teste = new HashSet<tb_teste>();
            this.tb_contato = new HashSet<tb_contato>();
            this.tb_email = new HashSet<tb_email>();
        }
    
        public int user_in_id { get; set; }
        public string user_st_nome { get; set; }
        public string user_st_sexo { get; set; }
        public System.DateTime user_dt_dtNasc { get; set; }
        public string user_st_username { get; set; }
        public string user_st_senha { get; set; }
        public string user_st_uf { get; set; }
        public string user_st_cidade { get; set; }
        public int user_in_nivelAcad { get; set; }
        public System.DateTime user_dt_dtCad { get; set; }
        public byte user_bool_fezTeste { get; set; }
        public string user_img_avatar { get; set; }
        public string user_st_bio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_detalhesResultado> tb_detalhesResultado { get; set; }
        public virtual tb_nivelAcademico tb_nivelAcademico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_teste> tb_teste { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_contato> tb_contato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_email> tb_email { get; set; }
    }
}
