//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerenciador.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_relatorioNotaMec
    {
        public int id_facul { get; set; }
        public string nome_facul { get; set; }
        public string uf_facul { get; set; }
        public int id_curso { get; set; }
        public string nome_curso { get; set; }
        public string desc_area { get; set; }
        public int valor_notaMec { get; set; }
    }
}
