//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerenciador.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_relatorioResultado
    {
        public int id_user { get; set; }
        public string username_user { get; set; }
        public int id_teste { get; set; }
        public System.DateTime inicio_teste { get; set; }
        public Nullable<System.DateTime> final_teste { get; set; }
        public Nullable<int> tempo_resultado { get; set; }
        public double exatas_resultado { get; set; }
        public double humanas_resultado { get; set; }
        public double biologicas_resultado { get; set; }
        public string nome_curso { get; set; }
        public string desc_curso { get; set; }
        public string tipo_curso { get; set; }
        public string duracao_curso { get; set; }
        public string desc_area { get; set; }
        public string img_curso { get; set; }
        public string nome_facul { get; set; }
        public string estado_facul { get; set; }
        public string site_facul { get; set; }
        public int valor_notaMec { get; set; }
        public byte novo_teste { get; set; }
    }
}
