//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerenciador.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_relatorioUsuario
    {
        public int id_user { get; set; }
        public string nome_user { get; set; }
        public string desc_email { get; set; }
        public string sexo_user { get; set; }
        public System.DateTime nasc_user { get; set; }
        public string username_user { get; set; }
        public string uf_user { get; set; }
        public string cidade_user { get; set; }
        public string desc_nivelAcad { get; set; }
        public string desc_tipoCont { get; set; }
        public string desc_cont { get; set; }
        public System.DateTime dtCad_user { get; set; }
        public byte teste_user { get; set; }
    }
}
