//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerenciador.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_relatorioFaculdades
    {
        public int id_facul { get; set; }
        public string nome_facul { get; set; }
        public string endereco_facul { get; set; }
        public string uf_facul { get; set; }
        public string estado_facul { get; set; }
        public string cidade_facul { get; set; }
        public string tipoContado_facul { get; set; }
        public string contato_facul { get; set; }
        public string site_facul { get; set; }
    }
}
