//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerenciador.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_RelatorioQuestoes
    {
        public int id_pergunta { get; set; }
        public string desc_pergunta { get; set; }
        public int id_resposta { get; set; }
        public string desc_resposta { get; set; }
        public double perc_exatas { get; set; }
        public double perc_humanas { get; set; }
        public double perc_biologicas { get; set; }
    }
}
