//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerenciador.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_RelatorioCurso
    {
        public int id_curso { get; set; }
        public string nome_curso { get; set; }
        public string desc_curso { get; set; }
        public string desc_area { get; set; }
        public string tipo_curso { get; set; }
        public string imagem_curso { get; set; }
        public string duracao_curso { get; set; }
        public int valor_max { get; set; }
        public int valor_min { get; set; }
    }
}
